//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiQuiniela.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupos
    {
        public Grupos()
        {
            this.UsuarioGrupoes = new HashSet<UsuarioGrupo>();
            this.Quinielas = new HashSet<Quiniela>();
        }
    
        public int ID_Grupo { get; set; }
        public Nullable<int> ID_Usuario { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> FechaIns { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<UsuarioGrupo> UsuarioGrupoes { get; set; }
        public virtual ICollection<Quiniela> Quinielas { get; set; }
    }
}
