//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiQuiniela.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partido
    {
        public Partido()
        {
            this.Quinielas = new HashSet<Quiniela>();
        }
    
        public int ID_Partido { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Equipo1 { get; set; }
        public Nullable<int> GolesEquipo1 { get; set; }
        public string Equipo2 { get; set; }
        public Nullable<int> GolesEquipo2 { get; set; }
        public string Ganador { get; set; }
        public string Ronda { get; set; }
    
        public virtual ICollection<Quiniela> Quinielas { get; set; }
    }
}
