//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiQuiniela.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuinielaEntities : DbContext
    {
        public QuinielaEntities()
            : base("name=QuinielaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Grupos> Grupos { get; set; }
        public DbSet<Partido> Partidos { get; set; }
        public DbSet<Quiniela> Quinielas { get; set; }
        public DbSet<UsuarioGrupo> UsuarioGrupoes { get; set; }
        public DbSet<Usuario> Usuarios { get; set; }
        public DbSet<RankingView> RankingViews { get; set; }
    }
}
