//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiQuiniela.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quiniela
    {
        public int ID_Usuario { get; set; }
        public int ID_Partido { get; set; }
        public Nullable<System.DateTime> FechaIns { get; set; }
        public Nullable<System.DateTime> FechaMod { get; set; }
        public Nullable<int> GolesEquipo1 { get; set; }
        public Nullable<int> GolesEquipo2 { get; set; }
        public string Ganador { get; set; }
        public Nullable<int> ID_Grupo { get; set; }
    
        public virtual Partido Partido { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Grupos Grupos { get; set; }
    }
}
