//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiQuiniela.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Grupos = new HashSet<Grupos>();
            this.Quinielas = new HashSet<Quiniela>();
            this.UsuarioGrupoes = new HashSet<UsuarioGrupo>();
        }
    
        public int ID_Usuario { get; set; }
        public string Nickname { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> FechaIns { get; set; }
        public string ID_Facebook { get; set; }
    
        public virtual ICollection<Grupos> Grupos { get; set; }
        public virtual ICollection<Quiniela> Quinielas { get; set; }
        public virtual ICollection<UsuarioGrupo> UsuarioGrupoes { get; set; }
    }
}
